---
namespace: mistermiles
name: gpg2_key_import
version: 1.0.3
readme: README.md
authors:
  - Alexis Miles Oortmann (@MisterMiles) <mister_dev@mailbox.org>
description: This Ansible role imports your personal gpg2 key into your infrastructure
license_file: LICENSE
dependencies: { }
tags:
  - gpg2
  - pgp
  - openpgp
  - gnupg2
repository: https://github.com/MisterMiles/gpg2-key-import
documentation: https://github.com/MisterMiles/gpg2-key-import
issues: https://github.com/MisterMiles/gpg2-key-import/issues
