---
namespace: mistermiles
name: gpg_key_import
version: 1.0.3
readme: README.md
authors:
  - Alexis Miles Oortmann (@MisterMiles) <mister_dev@mailbox.org>
description: This Ansible role imports your personal gpg key into your infrastructure
license_file: LICENSE
dependencies: { }
tags:
  - gpg
  - pgp
  - openpgp
  - import
  - gnupg
repository: https://github.com/MisterMiles/gpg-key-import
documentation: https://github.com/MisterMiles/gpg-key-import
issues: https://github.com/MisterMiles/gpg-key-import/issues
